new TypeIt("#memtitle", {
        speed: 50,
      })
        .type("Talant", { delay: 300 })
        .move(-2)
        .delete(1)
        .type("e")
        .move(null, { to: "END" })
        .type(" wins gamss")
        .pause(300)
        .delete(2)
        .type("es, but teawork")
        .move(-4)
        .type("m")
        .move(null, { to: "END" })
        .type(" andintelligence")
        .pause(500)
        .move(-12)
        .type(" ")
        .move(null, { to: "END" })
        .type(" win championships.")
        .break({ delay: 500 })
        .break({ delay: 500 })
        .type("<em>- Team mtx</em>")
        .delete(3)
        .type("<em>MTX</em>")
        .pause(5000)
        .delete(79)
        .go();
